theme: jekyll-theme-cayman
title: Welcome to Driss Guessous' datascience homepage!
descreiption: I am a recent Physics and Mathematics graduate who is seeking a job in Data Science and Machine Learning. This page is a place to show some of the projects I am working on.
